apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage-portal.fullname" . }}-config
  labels:
    {{- include "backstage-portal.labels" . | nindent 4 }}
data:
  app-config.kubernetes.yaml: |
    {{- $cfg := .Values.config | deepCopy }}
    {{- $dbPath := ":memory:" }}
    {{- if .Values.persistence.enabled }}
    {{- $dbPath = printf "%s/backstage.sqlite" .Values.persistence.mountPath }}
    {{- end }}
    {{- $_ := set $cfg.backend.database "connection" $dbPath }}
{{ $cfg | toYaml | indent 4 }}
