apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage-portal.fullname" . }}-config
  labels:
    {{- include "backstage-portal.labels" . | nindent 4 }}
data:
  app-config.kubernetes.yaml: |
{{ .Values.config | toYaml | indent 4 }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backstage-portal.serviceAccountName" . }}
  labels:
    {{- include "backstage-portal.labels" . | nindent 4 }}
{{- end }}
