"""The live release model: release_details.json -> the repo's updater script.

A release is a FILE-SET (artefact.json, sdlc-governance templates, per-env
governed-deploy workflows) present on every branch, generated by the deployment
repo's own updater script from a TRANSIENT release_details.json, then promoted
feature branch -> SIT -> UAT -> PRD/PRL1.

The agent orchestrates the script rather than reimplementing it:

  prepare : check out SIT's tip (Dulwich, no git binary — see git_snapshot),
            write the transient release_details.json to a temp dir OUTSIDE
            the repo, run the repo's updater script, stage what it changed.
            Nothing is written to GitHub. Returns a preview: changed files,
            env partition, RCTL timeline.
  apply   : commit the staged file-set onto SIT's tip and create
            release/<slug> through the Git Data API, open the release PR
            (feature -> SIT) with a machine-readable changed-files marker,
            auto-merge (or report pending), clean the workdir.
  promote : copy the release's changed file-set VERBATIM from the release
            branch to the next branch (SIT -> UAT -> PRD/PRL1) via a
            short-lived change branch + PR — same targeted mechanism as chart
            promotion, but raw file contents (workflow YAMLs are not JSON).

release_details.json is never committed anywhere, matching the live process.
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import uuid

from pydantic import BaseModel, Field

from ._common import (
    settings,
    tool,
    _get_github_client,
    _resolve_github_token,
    active_deploy_repo,
)
from . import git_snapshot, release_chain
from . import attribution
from .promotion import _merge_pr
from .release_window import _open_prd_pr_blocker

_FILES_MARKER = "RELEASE-FILES-JSON:"


# --- payload validation ------------------------------------------------------
def _slugify(name: str) -> str:
    out, prev_dash = [], False
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
            prev_dash = False
        elif not prev_dash and out:
            out.append("-")
            prev_dash = True
    return "".join(out).strip("-") or "release"


def _artifact_name_version(url: str) -> tuple[str, str] | None:
    last = url.rstrip("/").split("/")[-1]
    if ":" not in last:
        return None
    name, _, version = last.partition(":")
    return (name, version) if name and version else None


def normalize_artifact(entry: str) -> str:
    """Full URL passes through; bare name:version gets the artifactory base."""
    entry = entry.strip()
    if "://" in entry:
        return entry
    base = settings.artifactory_base_url.rstrip("/")
    return f"{base}/{entry}" if base else entry


def _valid_datetime(value: str) -> bool:
    from datetime import datetime

    try:
        datetime.strptime(value.replace("  ", " "), "%Y-%m-%d %H:%M:%S")
        return True
    except (ValueError, TypeError):
        return False


def validate_release(payload: dict) -> tuple[dict | None, list[str]]:
    """Hard validation the live script only warns about. Returns (details, errors)."""
    errors: list[str] = []
    required = ["release_name", "start_date", "end_date", "change_initiator", "change_summary"]
    for key in required:
        if not str(payload.get(key) or "").strip():
            errors.append(f"'{key}' is required.")

    for key in ("start_date", "end_date"):
        v = str(payload.get(key) or "")
        if v and not _valid_datetime(v):
            errors.append(f"'{key}' must be 'YYYY-MM-DD HH:MM:SS' (got {v!r}).")
    if not errors and payload.get("start_date") >= payload.get("end_date"):
        errors.append("'end_date' must be after 'start_date'.")

    artifacts = [normalize_artifact(a) for a in (payload.get("artefact") or []) if str(a).strip()]
    if not artifacts:
        errors.append("At least one artifact is required.")
    names: list[str] = []
    for url in artifacts:
        nv = _artifact_name_version(url)
        if nv is None:
            errors.append(f"Artifact has no ':version': {url}")
        else:
            if nv[0] in names:
                errors.append(f"Duplicate service in artifacts: {nv[0]}")
            names.append(nv[0])

    for key in ("prl1_only", "df_images"):
        for svc in payload.get(key) or []:
            if svc and svc not in names:
                errors.append(
                    f"'{key}' names a service not in the artifact list: {svc!r} "
                    "(a typo here would silently misroute the release)."
                )

    # Optional target deployment repo (owner/repo). Validated here but kept OUT
    # of the details dict — release_details.json must stay exactly the shape the
    # live updater script consumes.
    repo = str(payload.get("deployment_repo") or "").strip()
    if repo and ("/" not in repo or repo.startswith("/") or repo.endswith("/")):
        errors.append(f"'deployment_repo' must be owner/repo (got {repo!r}).")
    kind = str(payload.get("release_kind") or "").strip().lower()
    if kind and kind not in release_chain.KINDS:
        errors.append(f"'release_kind' must be care or df (got {kind!r}).")

    if errors:
        return None, errors

    details = {
        "release_name": payload["release_name"].strip(),
        "start_date": payload["start_date"].strip(),
        "end_date": payload["end_date"].strip(),
        "change_initiator": payload["change_initiator"].strip(),
        "change_summary": payload["change_summary"].strip(),
        "change_description": str(payload.get("change_description") or "").strip(),
        "change_reason": str(payload.get("change_reason") or "").strip(),
        "associated_risk": str(payload.get("associated_risk") or "").strip(),
        "consequence": str(payload.get("consequence") or "").strip(),
        "user_service_impact": str(payload.get("user_service_impact") or "").strip(),
        "prl1_only": [s for s in (payload.get("prl1_only") or []) if s],
        "df_images": [s for s in (payload.get("df_images") or []) if s],
        "artefact": artifacts,
    }
    return details, []


def partition_environments(details: dict) -> dict:
    """Which services land where — mirrors the updater script's routing rules."""
    names = [nv[0] for a in details["artefact"] if (nv := _artifact_name_version(a))]
    prl1_only, df = set(details["prl1_only"]), set(details["df_images"])
    deployable = [n for n in names if n not in df]
    standard = [n for n in deployable if n not in prl1_only]
    restricted = [n for n in deployable if n in prl1_only]
    return {
        "prd": standard,
        "uat": standard + restricted,
        "prl1": standard + restricted,
        "dataflow_only": sorted(df),
        "prl1_only": restricted,
    }


# --- prepare / apply ---------------------------------------------------------
def _run(cmd: list[str], cwd: str, timeout: int = 120) -> tuple[int, str]:
    # No .pyc files: the updater's own imports must not show up as changed files.
    env = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout, env=env)
    return r.returncode, (r.stdout + r.stderr).strip()


def prepare_release_fileset(payload: dict, _keep_workdir: bool = False) -> dict:
    """Generate the release file-set locally (no push). Returns preview or errors."""
    details, errors = validate_release(payload)
    if errors:
        return {"ok": False, "errors": errors}

    kind = release_chain.kind_of(details, str(payload.get("release_kind") or "").strip().lower())
    # Form-supplied target repo wins; empty falls back to this kind's repo.
    repo_full = str(payload.get("deployment_repo") or "").strip() or (
        (settings.df_release_repo if kind == "df" else "") or active_deploy_repo())
    landing = release_chain.landing(kind)
    try:
        gh_repo = _get_github_client().get_repo(repo_full)
        blocker = _open_prd_pr_blocker(gh_repo, branches=release_chain.guard_branches(kind))
    except Exception as e:
        return {"ok": False, "errors": [f"Could not reach {repo_full}: {e}"]}
    if blocker is not None:
        return {
            "ok": False,
            "errors": [
                f"A release is already in flight: PR #{blocker.number} "
                f"({blocker.head.ref} → {blocker.base.ref}, {blocker.html_url}). "
                "One release at a time — merge or close it first."
            ],
        }

    branch = f"release/{_slugify(details['release_name'])}"
    workdir = tempfile.mkdtemp(prefix="release-fileset-")
    repo_dir = os.path.join(workdir, "repo")
    try:
        git_snapshot.clone_branch(
            git_snapshot.repo_url(repo_full), landing, repo_dir,
            _resolve_github_token() or "",
        )

        # Transient release_details.json — OUTSIDE the repo so it can never be committed.
        details_path = os.path.join(workdir, "release_details.json")
        with open(details_path, "w", encoding="utf-8") as f:
            json.dump(details, f, indent=2)

        script = os.path.join(repo_dir, settings.release_updater_script)
        if not os.path.isfile(script):
            # Three settings decide this — the repo, the branch it landed on, and
            # the path — so naming only the path sends people to the wrong one.
            # Say which repo and branch were actually searched, and show what IS
            # in the directory (or that the directory is missing), because the
            # usual causes are a DF repo that keeps the script elsewhere and a
            # landing branch that simply does not carry it.
            where = os.path.dirname(script) or repo_dir
            if os.path.isdir(where):
                names = sorted(os.listdir(where))[:12]
                found = ("directory holds: " + ", ".join(names)) if names else "that directory is empty"
            else:
                rel = os.path.relpath(where, repo_dir)
                found = f"there is no {rel}/ directory on this branch"
            raise RuntimeError(
                f"updater script not found at {settings.release_updater_script} "
                f"in {repo_full} on branch {landing} — {found}. "
                f"Point RELEASE_UPDATER_SCRIPT at the real path, or land the release "
                f"on a branch that carries the script (DF_RELEASE_BRANCHES)."
            )
        rc, script_output = _run(
            [sys.executable, script, "--release-details-file", details_path],
            cwd=repo_dir, timeout=180,
        )
        if rc != 0:
            raise RuntimeError(f"updater script failed:\n{script_output[-800:]}")

        changed_files = git_snapshot.changed_paths(git_snapshot.stage_all(repo_dir))
        if not changed_files:
            raise RuntimeError("updater script produced no file changes")

        # RCTL timeline read back from the file the script just generated.
        timeline = []
        try:
            with open(os.path.join(repo_dir, "sdlc-governance/RCTLDEF0000104.json")) as f:
                rctl = json.load(f)
            for step in rctl.get("implementationSteps", []):
                timeline.append(f"{step.get('step')}: {step.get('implementationStart')} -> {step.get('implementationEnd')}")
            for step in rctl.get("rollbackSteps", []):
                timeline.append(f"[rollback] {step.get('step')}: {step.get('rollbackStart')} -> {step.get('rollbackEnd')}")
        except Exception:
            pass
    except Exception as e:
        shutil.rmtree(workdir, ignore_errors=True)
        return {"ok": False, "errors": [str(e)]}

    artifact_pairs = [
        {"name": nv[0], "tag": nv[1]}
        for a in details["artefact"]
        if (nv := _artifact_name_version(a))
    ]
    # Fingerprint what was generated, then THROW THE CLONE AWAY. The prepared
    # file-set used to survive as a directory on this machine, which tied the
    # confirmation to this process: another replica — or this one after a
    # restart — had a valid token and no files. Apply regenerates from
    # ``details`` (pure data) and refuses unless it reproduces this fingerprint,
    # which also catches SIT moving between preview and confirm: previously that
    # pushed a branch built on an older SIT and said nothing.
    fileset_hash = _fileset_fingerprint(repo_dir, changed_files)
    # apply regenerates and needs the clone it just made; preview does not and
    # must not leave one behind, because that is the state that pinned a
    # confirmation to one process.
    if not _keep_workdir:
        shutil.rmtree(workdir, ignore_errors=True)
    return {
        "ok": True,
        "release_name": details["release_name"],
        "branch": branch,
        **({"workdir": workdir} if _keep_workdir else {}),
        "details": details,             # the inputs apply regenerates from
        "fileset_hash": fileset_hash,
        "deployment_repo": repo_full,
        "kind": kind,
        "landing_branch": landing,
        "artifacts": artifact_pairs,
        "preview": {
            "release": details["release_name"],
            "window": f"{details['start_date']} -> {details['end_date']}",
            "initiator": details["change_initiator"],
            "deployment_repo": repo_full,
            "lands_on": landing,
            "changed_files": changed_files,
            "environments": partition_environments(details),
            "rctl_timeline": timeline,
        },
    }


def _fileset_fingerprint(repo_dir: str, changed_files: list[str]) -> str:
    """A stable hash of the generated file-set: path + content, in path order.

    The deploy repo's updater script is deterministic — verified by generating
    the same release twice and diffing every file — so an identical input must
    reproduce an identical hash. Anything else means the inputs or the base
    branch moved, and the approval no longer describes what would be pushed.
    """
    digest = hashlib.sha256()
    for rel in sorted(changed_files):
        digest.update(rel.encode())
        path = os.path.join(repo_dir, rel)
        if os.path.isfile(path):
            with open(path, "rb") as handle:
                digest.update(handle.read())
    return digest.hexdigest()


def apply_release_fileset(prep: dict) -> dict:
    """Push the release branch, open + auto-merge the release PR into SIT.

    Regenerates the file-set from the prepared inputs rather than relying on a
    directory this process happens to still hold, so the confirmation can be
    applied by any replica. Refuses if the regenerated set does not match the
    fingerprint taken at preview time — what gets pushed is then exactly what
    was approved, or nothing is pushed at all.
    """
    workdir = prep.get("workdir")
    branch = prep.get("branch")
    if not workdir or not os.path.isdir(os.path.join(workdir, "repo")):
        details, expected = prep.get("details"), prep.get("fileset_hash")
        if not details:
            return {"ok": False, "error": "Prepared release is incomplete — start the release again."}
        # details is exactly release_details.json, which carries neither the
        # target repo nor the kind — found in testing: without them a DF release
        # in its own repo regenerated against the CARE repo.
        regenerated = prepare_release_fileset(
            {**details, "deployment_repo": prep.get("deployment_repo") or "",
             "release_kind": prep.get("kind") or ""},
            _keep_workdir=True,
        )
        if not regenerated.get("ok"):
            return {"ok": False,
                    "error": "; ".join(regenerated.get("errors", ["could not regenerate the release"]))}
        if expected and regenerated.get("fileset_hash") != expected:
            before = set(prep.get("preview", {}).get("changed_files") or [])
            after = set(regenerated.get("preview", {}).get("changed_files") or [])
            moved = sorted((before ^ after)) or ["file contents changed"]
            return {
                "ok": False,
                "error": ("The release no longer matches what you approved — "
                          f"{', '.join(moved[:6])}. The base branch or the inputs moved "
                          "since the preview. Start the release again."),
            }
        prep = {**prep, **regenerated}
        workdir, branch = prep.get("workdir"), prep.get("branch")
    repo_dir = os.path.join(workdir or "", "repo")
    if not workdir or not os.path.isdir(repo_dir):
        return {"ok": False, "error": "Prepared release workdir is gone — start the release again."}
    try:
        repo_full = prep.get("deployment_repo") or active_deploy_repo()
        gh_repo = _get_github_client().get_repo(repo_full)
        initiator = (prep.get("details") or {}).get("change_initiator") or ""
        # The verified caller authors the commit; the typed initiator is the
        # fallback when identity is off (a claim, so never over a verified name).
        author_name, author_email = attribution.author() or (
            initiator.split("@")[0] or "release-copilot", initiator or "release-copilot@localhost")
        try:
            sha = git_snapshot.commit_via_api(
                gh_repo, repo_dir, git_snapshot.stage_all(repo_dir),
                git_snapshot.base_commit(repo_dir),
                attribution.with_trailer(prep.get("release_name") or branch),
                author_name, author_email,
            )
            gh_repo.create_git_ref(f"refs/heads/{branch}", sha)
        except Exception as e:  # noqa: BLE001 — nothing was pushed; say why
            msg = str(getattr(e, "data", None) or e)
            if "already exists" in msg.lower():
                msg = f"branch {branch} already exists in {repo_full} — delete it or pick another release name"
            return {"ok": False, "error": f"could not create {branch}: {msg[:400]}"}
        preview = prep.get("preview", {})
        body = (
            f"Release **{prep.get('release_name')}** — file-set generated by "
            f"`{settings.release_updater_script}` from a transient release_details.json.\n\n"
            f"Window: {preview.get('window')}\nInitiator: {preview.get('initiator')}\n\n"
            f"{_FILES_MARKER} {json.dumps(preview.get('changed_files', []))}\n"
        )
        kind = prep.get("kind") or "care"
        landing = prep.get("landing_branch") or release_chain.landing(kind)
        pr = gh_repo.create_pull(
            title=prep.get("release_name"), body=attribution.with_trailer(body),
            head=branch, base=landing,
        )
        merged, detail = _merge_pr(pr, "merge")
        note = (
            f"Release PR #{pr.number} ({pr.html_url}) {'merged into' if merged else 'opened against'} "
            f"{landing}{'' if merged else f' — {detail}'}. {release_chain.next_steps(kind)}"
        )
        if merged:
            # Drain the intake queue: shipped charts get 'released' events so next
            # week starts clean. Best-effort — never fails the release.
            try:
                from . import release_queue as _rq

                _rq.mark_released(
                    prep.get("release_name") or "", pr.number, prep.get("artifacts") or [],
                    deployment_repo=repo_full,
                )
            except Exception:
                pass
        return {
            "ok": True,
            "action": "release_created",
            "release_name": prep.get("release_name"),
            "branch": branch,
            "deployment_repo": repo_full,
            "pr_number": pr.number,
            "pr_url": pr.html_url,
            "merged_to_sit": merged,
            "changed_files": preview.get("changed_files", []),
            "note": note,
        }
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def cleanup_prepared_release(prep: dict) -> None:
    """Drop a prepared-but-unconfirmed release's workdir."""
    workdir = (prep or {}).get("workdir")
    if workdir:
        shutil.rmtree(workdir, ignore_errors=True)


# --- promotion of the file-set ----------------------------------------------
def _latest_release_pr(gh_repo, kinds=("care",)):
    """(PR, kind): the most recent release PR carrying the changed-files marker,
    looking on each kind's landing branch. Several kinds may share a repo, so
    the newest (highest-numbered) wins — PR numbers only grow."""
    import itertools

    best = (None, "")
    seen = set()
    for kind in kinds:
        landing = release_chain.landing(kind)
        if landing in seen:
            continue
        seen.add(landing)
        for state in ("open", "closed"):
            found = next((pr for pr in itertools.islice(
                gh_repo.get_pulls(state=state, base=landing, sort="created", direction="desc"), 30)
                if pr.head.ref.startswith("release/") and _FILES_MARKER in (pr.body or "")), None)
            if found is not None:
                if best[0] is None or found.number > best[0].number:
                    best = (found, kind)
                break
    return best


def _release_files_from_pr(pr) -> list[str]:
    body = pr.body or ""
    idx = body.find(_FILES_MARKER)
    if idx == -1:
        return []
    line = body[idx + len(_FILES_MARKER):].strip().splitlines()[0]
    try:
        files = json.loads(line)
        return [f for f in files if isinstance(f, str)]
    except json.JSONDecodeError:
        return []


def _read_raw(gh_repo, path: str, ref: str) -> str | None:
    try:
        return gh_repo.get_contents(path, ref=ref).decoded_content.decode("utf-8")
    except Exception:
        return None


def _workflow_chart_entries(text: str) -> list[dict[str, str]]:
    """Chart name:version pairs from a governed-deploy workflow's
    multi_deployments_json block (line scan — the block is JSON-in-YAML).
    This is the exact deploy set for that environment: prl1_only charts are
    absent from the PRD workflow, df_images from all of them."""
    entries: list[dict[str, str]] = []
    name = None
    for line in (text or "").splitlines():
        s = line.strip().rstrip(",")
        if '"helm_chart_name"' in s and ":" in s:
            name = s.split(":", 1)[1].strip().strip('"')
        elif '"helm_chart_version"' in s and ":" in s and name:
            entries.append({"name": name, "tag": s.split(":", 1)[1].strip().strip('"')})
            name = None
    return entries


_ARTEFACT_FILE = "artefact-provider/artefact.json"


def _promoted_artifacts(gh_repo, kind: str, env: str, files: list[str], release_branch: str):
    """What a promotion put into ``env``, for the event log — read ONLY from files
    the release itself generated. Found live: a DF promotion read the CARE helm
    workflow that happened to sit on the branch (a DF release never writes it)
    and logged a chart that was not in the release at all.

    CARE: the env's governed-deploy workflow (its exact helm deploy set).
    DF:   the release's artefact list — DF images never enter helm workflows.
    """
    if kind == "df":
        if _ARTEFACT_FILE not in files:
            return []
        try:
            data = json.loads(_read_raw(gh_repo, _ARTEFACT_FILE, release_branch) or "{}")
        except json.JSONDecodeError:
            return []
        return [{"name": nv[0], "tag": nv[1]} for a in (data.get("artefact") or [])
                if isinstance(a, str) and (nv := _artifact_name_version(a))]
    workflow = f".github/workflows/deploy_with_sdlc_governance_{env}.yaml"
    if workflow not in files:
        return []
    return _workflow_chart_entries(_read_raw(gh_repo, workflow, release_branch) or "")


class PromoteReleaseInput(BaseModel):
    target: str = Field(..., description="Environment to promote the release file-set to: uat, prd, or prl1 "
                                         "(a DF release lands on its UAT branch directly — promote it to prd).")
    release_branch: str = Field(
        default="",
        description="Release branch (release/<slug>). Empty = the latest release PR's branch.",
    )
    deployment_repo: str = Field(
        default="",
        description="Deployment repo (owner/repo) the release lives in. Empty = the configured default.",
    )
    kind: str = Field(
        default="",
        description="'df' for the Dataflow release, 'care' for the CARE release. Empty = work it out "
                    "from the repo and the latest release PR.",
    )


@tool(args_schema=PromoteReleaseInput)
def promote_release(target: str, release_branch: str = "", deployment_repo: str = "", kind: str = "") -> str:
    """Promote the current release's FILE-SET to the next environment branch of its
    chain (CARE: SIT -> UAT -> PRD/PRL1; DF: DF_RELEASE_BRANCHES, e.g. RELEASE_UAT ->
    RELEASE_PRD): copies the release's changed files verbatim onto the target via
    a short-lived change branch + PR (auto-merged when allowed)."""
    t = target.strip().lower()
    kind = kind.strip().lower()
    if kind and kind not in release_chain.KINDS:
        return json.dumps({"ok": False, "error": f"Unknown release kind '{kind}' (use care or df)."})
    try:
        repo_full = str(deployment_repo or "").strip() or (
            (settings.df_release_repo if kind == "df" else "") or active_deploy_repo())
        gh_repo = _get_github_client().get_repo(repo_full)
    except Exception as e:
        return json.dumps({"ok": False, "error": f"GitHub error: {e}"})

    # Which kind's chain: given, or the repo's own (a separate DF repo is DF),
    # or whichever kind has the newest release PR in a shared repo.
    df_repo = (settings.df_release_repo or "").strip()
    if kind:
        kinds = (kind,)
    elif df_repo and repo_full == df_repo and df_repo != settings.deploy_repo:
        kinds = ("df",)
    else:
        kinds = ("care", "df")
    pr, found_kind = _latest_release_pr(gh_repo, kinds)
    kind = found_kind or kinds[0]
    branch_map = release_chain.targets(kind)
    if t not in branch_map:
        envs = [e for e in branch_map if e != "prod"]
        lands = release_chain.landing(kind)
        why = (f"the {kind.upper()} release lands on {lands} directly" if t == release_chain.chain(kind)[0][0]
               else f"unknown target '{target}'")
        return json.dumps({"ok": False, "error": f"Cannot promote to {target}: {why} — use {' or '.join(envs)}."})
    target_branch = branch_map[t]

    if not release_branch:
        if pr is None:
            return json.dumps({"ok": False, "error": "No release PR with a file marker found — create a release first."})
        release_branch = pr.head.ref
        files = _release_files_from_pr(pr)
    else:
        files = _release_files_from_pr(pr) if pr and pr.head.ref == release_branch else []
    if not files:
        return json.dumps({"ok": False, "error": f"Could not determine the release file list for {release_branch}."})

    # Copy the file-set verbatim from the release branch onto a change branch of target.
    work = f"change/release/{uuid.uuid4().hex[:8]}"
    try:
        base_ref = gh_repo.get_git_ref(f"heads/{target_branch}")
        gh_repo.create_git_ref(f"refs/heads/{work}", base_ref.object.sha)
        changed = []
        for path in files:
            content = _read_raw(gh_repo, path, release_branch)
            if content is None:
                continue
            current = _read_raw(gh_repo, path, work)
            if current == content:
                continue
            message = attribution.with_trailer(f"Promote release file {path} -> {target_branch}")
            who = attribution.author_kwargs()
            try:
                existing = gh_repo.get_contents(path, ref=work)
                gh_repo.update_file(path, message, content, existing.sha, branch=work, **who)
            except Exception:
                gh_repo.create_file(path, message, content, branch=work, **who)
            changed.append(path)
        if not changed:
            try:
                gh_repo.get_git_ref(f"heads/{work}").delete()
            except Exception:
                pass
            return json.dumps({
                "ok": True, "action": "no_change",
                "note": f"{target_branch} already carries the release file-set.",
            })
        release_name = (pr.title if pr else release_branch)
        promo_pr = gh_repo.create_pull(
            title=f"{release_name} (→ {target_branch})",
            body=attribution.with_trailer(f"Promotes the release file-set from {release_branch}."),
            head=work, base=target_branch,
        )
        merged, detail = _merge_pr(promo_pr, "squash")
        # BQ capture: the promoted env's governance workflow on the release
        # branch IS that env's exact deploy set — one event per chart so
        # per-environment state/stats include UAT/PRD/PRL1 promotions. Merged →
        # 'deployed' now. Refused by branch protection → 'pending' against this
        # PR, settled by pr_reconcile when someone merges it in GitHub (a single
        # PR, so its merge is what completes the promotion). Best-effort; never
        # fails the promotion.
        try:
            from . import release_queue as _rq

            key = "prd" if t in ("prd", "prod") else t
            charts = _promoted_artifacts(gh_repo, kind, key, files, release_branch)
            if charts and merged:
                _rq.record_deployment(
                    environment=key,
                    artifacts=charts,
                    deployment_repo=repo_full,
                    pr_number=promo_pr.number,
                    note="release_promoted",
                )
            elif charts:
                from .pr_reconcile import record_pending

                record_pending(key, charts, repo_full, promo_pr.number,
                               on_merge="deployed", tag="release_promoted")
        except Exception:
            pass
        return json.dumps({
            "ok": True,
            "action": "release_promoted" if merged else "promotion_pending",
            "target": target_branch,
            "files": changed,
            "pr_number": promo_pr.number,
            "pr_url": promo_pr.html_url,
            "note": (
                f"Release file-set promoted to {target_branch} via "
                f"[PR #{promo_pr.number}]({promo_pr.html_url}) (merged)."
                if merged else
                f"Raised [PR #{promo_pr.number}]({promo_pr.html_url}) to promote the release "
                f"file-set to {target_branch} — awaiting approval, NOT promoted yet: {detail}. "
                f"{target_branch} is unchanged until it merges."
            ),
        }, indent=2)
    except Exception as e:
        return json.dumps({"ok": False, "error": f"Promotion failed: {e}"})
