"""The live release model: release_details.json -> the repo's updater script.

A release is a FILE-SET (artefact.json, sdlc-governance templates, per-env
governed-deploy workflows) present on every branch, generated by the deployment
repo's own updater script from a TRANSIENT release_details.json, then promoted
feature branch -> SIT -> UAT -> PRD/PRL1.

The agent orchestrates the script rather than reimplementing it:

  prepare : clone the deploy repo, cut release/<slug> from SIT, write the
            transient release_details.json to a temp dir OUTSIDE the repo,
            run the repo's updater script, commit locally. Nothing is pushed.
            Returns a preview: changed files, env partition, RCTL timeline.
  apply   : push the branch, open the release PR (feature -> SIT) with a
            machine-readable changed-files marker, auto-merge (or report
            pending), clean the workdir.
  promote : copy the release's changed file-set VERBATIM from the release
            branch to the next branch (SIT -> UAT -> PRD/PRL1) via a
            short-lived change branch + PR — same targeted mechanism as chart
            promotion, but raw file contents (workflow YAMLs are not JSON).

release_details.json is never committed anywhere, matching the live process.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import uuid

from ._common import (
    settings,
    tool,
    BaseModel,
    Field,
    _get_github_client,
    _resolve_github_token,
    active_deploy_repo,
)
from .promotion import _merge_pr
from .release_window import _open_prd_pr_blocker

_FILES_MARKER = "RELEASE-FILES-JSON:"


# --- payload validation ------------------------------------------------------
def _slugify(name: str) -> str:
    out, prev_dash = [], False
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
            prev_dash = False
        elif not prev_dash and out:
            out.append("-")
            prev_dash = True
    return "".join(out).strip("-") or "release"


def _artifact_name_version(url: str) -> tuple[str, str] | None:
    last = url.rstrip("/").split("/")[-1]
    if ":" not in last:
        return None
    name, _, version = last.partition(":")
    return (name, version) if name and version else None


def normalize_artifact(entry: str) -> str:
    """Full URL passes through; bare name:version gets the artifactory base."""
    entry = entry.strip()
    if "://" in entry:
        return entry
    base = settings.artifactory_base_url.rstrip("/")
    return f"{base}/{entry}" if base else entry


def _valid_datetime(value: str) -> bool:
    from datetime import datetime

    try:
        datetime.strptime(value.replace("  ", " "), "%Y-%m-%d %H:%M:%S")
        return True
    except (ValueError, TypeError):
        return False


def validate_release(payload: dict) -> tuple[dict | None, list[str]]:
    """Hard validation the live script only warns about. Returns (details, errors)."""
    errors: list[str] = []
    required = ["release_name", "start_date", "end_date", "change_initiator", "change_summary"]
    for key in required:
        if not str(payload.get(key) or "").strip():
            errors.append(f"'{key}' is required.")

    for key in ("start_date", "end_date"):
        v = str(payload.get(key) or "")
        if v and not _valid_datetime(v):
            errors.append(f"'{key}' must be 'YYYY-MM-DD HH:MM:SS' (got {v!r}).")
    if not errors and payload.get("start_date") >= payload.get("end_date"):
        errors.append("'end_date' must be after 'start_date'.")

    artifacts = [normalize_artifact(a) for a in (payload.get("artefact") or []) if str(a).strip()]
    if not artifacts:
        errors.append("At least one artifact is required.")
    names: list[str] = []
    for url in artifacts:
        nv = _artifact_name_version(url)
        if nv is None:
            errors.append(f"Artifact has no ':version': {url}")
        else:
            if nv[0] in names:
                errors.append(f"Duplicate service in artifacts: {nv[0]}")
            names.append(nv[0])

    for key in ("prl1_only", "df_images"):
        for svc in payload.get(key) or []:
            if svc and svc not in names:
                errors.append(
                    f"'{key}' names a service not in the artifact list: {svc!r} "
                    "(a typo here would silently misroute the release)."
                )

    # Optional target deployment repo (owner/repo). Validated here but kept OUT
    # of the details dict — release_details.json must stay exactly the shape the
    # live updater script consumes.
    repo = str(payload.get("deployment_repo") or "").strip()
    if repo and ("/" not in repo or repo.startswith("/") or repo.endswith("/")):
        errors.append(f"'deployment_repo' must be owner/repo (got {repo!r}).")

    if errors:
        return None, errors

    details = {
        "release_name": payload["release_name"].strip(),
        "start_date": payload["start_date"].strip(),
        "end_date": payload["end_date"].strip(),
        "change_initiator": payload["change_initiator"].strip(),
        "change_summary": payload["change_summary"].strip(),
        "change_description": str(payload.get("change_description") or "").strip(),
        "change_reason": str(payload.get("change_reason") or "").strip(),
        "associated_risk": str(payload.get("associated_risk") or "").strip(),
        "consequence": str(payload.get("consequence") or "").strip(),
        "user_service_impact": str(payload.get("user_service_impact") or "").strip(),
        "prl1_only": [s for s in (payload.get("prl1_only") or []) if s],
        "df_images": [s for s in (payload.get("df_images") or []) if s],
        "artefact": artifacts,
    }
    return details, []


def partition_environments(details: dict) -> dict:
    """Which services land where — mirrors the updater script's routing rules."""
    names = [nv[0] for a in details["artefact"] if (nv := _artifact_name_version(a))]
    prl1_only, df = set(details["prl1_only"]), set(details["df_images"])
    deployable = [n for n in names if n not in df]
    standard = [n for n in deployable if n not in prl1_only]
    restricted = [n for n in deployable if n in prl1_only]
    return {
        "prd": standard,
        "uat": standard + restricted,
        "prl1": standard + restricted,
        "dataflow_only": sorted(df),
        "prl1_only": restricted,
    }


# --- prepare / apply ---------------------------------------------------------
def _run(cmd: list[str], cwd: str, timeout: int = 120) -> tuple[int, str]:
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
    return r.returncode, (r.stdout + r.stderr).strip()


def _authed_clone_url(repo_full: str) -> str:
    token = _resolve_github_token() or ""
    host = "github.com"
    if settings.github_base_url:
        host = settings.github_base_url.split("://")[-1].split("/")[0]
    return f"https://x-access-token:{token}@{host}/{repo_full}.git"


def prepare_release_fileset(payload: dict) -> dict:
    """Generate the release file-set locally (no push). Returns preview or errors."""
    details, errors = validate_release(payload)
    if errors:
        return {"ok": False, "errors": errors}

    # Form-supplied target repo wins; empty falls back to session/config default.
    repo_full = str(payload.get("deployment_repo") or "").strip() or active_deploy_repo()
    try:
        gh_repo = _get_github_client().get_repo(repo_full)
        blocker = _open_prd_pr_blocker(gh_repo)
    except Exception as e:
        return {"ok": False, "errors": [f"Could not reach {repo_full}: {e}"]}
    if blocker is not None:
        return {
            "ok": False,
            "errors": [
                f"A release is already in flight: PR #{blocker.number} "
                f"({blocker.head.ref} → {blocker.base.ref}, {blocker.html_url}). "
                "One release at a time — merge or close it first."
            ],
        }

    branch = f"release/{_slugify(details['release_name'])}"
    workdir = tempfile.mkdtemp(prefix="release-fileset-")
    repo_dir = os.path.join(workdir, "repo")
    try:
        rc, out = _run(
            ["git", "clone", "--depth", "50", "--branch", settings.sit_branch,
             _authed_clone_url(repo_full), repo_dir],
            cwd=workdir, timeout=180,
        )
        if rc != 0:
            raise RuntimeError(f"clone failed: {out[-500:]}")
        rc, out = _run(["git", "checkout", "-b", branch], cwd=repo_dir)
        if rc != 0:
            raise RuntimeError(f"branch failed: {out[-300:]}")

        # Transient release_details.json — OUTSIDE the repo so it can never be committed.
        details_path = os.path.join(workdir, "release_details.json")
        with open(details_path, "w", encoding="utf-8") as f:
            json.dump(details, f, indent=2)

        script = os.path.join(repo_dir, settings.release_updater_script)
        if not os.path.isfile(script):
            raise RuntimeError(f"updater script not found at {settings.release_updater_script}")
        rc, script_output = _run(
            [sys.executable, script, "--release-details-file", details_path],
            cwd=repo_dir, timeout=180,
        )
        if rc != 0:
            raise RuntimeError(f"updater script failed:\n{script_output[-800:]}")

        _run(["git", "add", "-A"], cwd=repo_dir)
        rc, staged = _run(["git", "diff", "--cached", "--name-only"], cwd=repo_dir)
        changed_files = sorted(line.strip() for line in staged.splitlines() if line.strip())
        if not changed_files:
            raise RuntimeError("updater script produced no file changes")
        author = f"{details['change_initiator'].split('@')[0]} <{details['change_initiator']}>"
        rc, out = _run(
            ["git", "-c", f"user.name={details['change_initiator'].split('@')[0]}",
             "-c", f"user.email={details['change_initiator']}",
             "commit", "--author", author, "-m", details["release_name"]],
            cwd=repo_dir,
        )
        if rc != 0:
            raise RuntimeError(f"commit failed: {out[-300:]}")

        # RCTL timeline read back from the file the script just generated.
        timeline = []
        try:
            with open(os.path.join(repo_dir, "sdlc-governance/RCTLDEF0000104.json")) as f:
                rctl = json.load(f)
            for step in rctl.get("implementationSteps", []):
                timeline.append(f"{step.get('step')}: {step.get('implementationStart')} -> {step.get('implementationEnd')}")
            for step in rctl.get("rollbackSteps", []):
                timeline.append(f"[rollback] {step.get('step')}: {step.get('rollbackStart')} -> {step.get('rollbackEnd')}")
        except Exception:
            pass
    except Exception as e:
        shutil.rmtree(workdir, ignore_errors=True)
        return {"ok": False, "errors": [str(e)]}

    artifact_pairs = [
        {"name": nv[0], "tag": nv[1]}
        for a in details["artefact"]
        if (nv := _artifact_name_version(a))
    ]
    return {
        "ok": True,
        "release_name": details["release_name"],
        "branch": branch,
        "workdir": workdir,
        "deployment_repo": repo_full,
        "artifacts": artifact_pairs,
        "preview": {
            "release": details["release_name"],
            "window": f"{details['start_date']} -> {details['end_date']}",
            "initiator": details["change_initiator"],
            "deployment_repo": repo_full,
            "changed_files": changed_files,
            "environments": partition_environments(details),
            "rctl_timeline": timeline,
        },
    }


def apply_release_fileset(prep: dict) -> dict:
    """Push the prepared branch, open + auto-merge the release PR into SIT."""
    workdir, branch = prep.get("workdir"), prep.get("branch")
    repo_dir = os.path.join(workdir or "", "repo")
    if not workdir or not os.path.isdir(repo_dir):
        return {"ok": False, "error": "Prepared release workdir is gone — start the release again."}
    try:
        rc, out = _run(["git", "push", "-u", "origin", branch], cwd=repo_dir, timeout=180)
        if rc != 0:
            return {"ok": False, "error": f"push failed: {out[-400:]}"}

        repo_full = prep.get("deployment_repo") or active_deploy_repo()
        gh_repo = _get_github_client().get_repo(repo_full)
        preview = prep.get("preview", {})
        body = (
            f"Release **{prep.get('release_name')}** — file-set generated by "
            f"`{settings.release_updater_script}` from a transient release_details.json.\n\n"
            f"Window: {preview.get('window')}\nInitiator: {preview.get('initiator')}\n\n"
            f"{_FILES_MARKER} {json.dumps(preview.get('changed_files', []))}\n"
        )
        pr = gh_repo.create_pull(
            title=prep.get("release_name"), body=body,
            head=branch, base=settings.sit_branch,
        )
        merged, detail = _merge_pr(pr, "merge")
        note = (
            f"Release PR #{pr.number} ({pr.html_url}) {'merged into' if merged else 'opened against'} "
            f"{settings.sit_branch}{'' if merged else f' — {detail}'}. "
            f"Promote with 'promote release to uat' then 'promote release to prd/prl1'."
        )
        if merged:
            # Drain the intake queue: shipped charts get 'released' events so next
            # week starts clean. Best-effort — never fails the release.
            try:
                from . import release_queue as _rq

                _rq.mark_released(
                    prep.get("release_name") or "", pr.number, prep.get("artifacts") or []
                )
            except Exception:
                pass
        return {
            "ok": True,
            "action": "release_created",
            "release_name": prep.get("release_name"),
            "branch": branch,
            "deployment_repo": repo_full,
            "pr_number": pr.number,
            "pr_url": pr.html_url,
            "merged_to_sit": merged,
            "changed_files": preview.get("changed_files", []),
            "note": note,
        }
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def cleanup_prepared_release(prep: dict) -> None:
    """Drop a prepared-but-unconfirmed release's workdir."""
    workdir = (prep or {}).get("workdir")
    if workdir:
        shutil.rmtree(workdir, ignore_errors=True)


# --- promotion of the file-set ----------------------------------------------
def _latest_release_pr(gh_repo):
    """Most recent release PR into SIT carrying the changed-files marker."""
    import itertools

    for state in ("open", "closed"):
        for pr in itertools.islice(
            gh_repo.get_pulls(state=state, base=settings.sit_branch, sort="created", direction="desc"), 30
        ):
            if pr.head.ref.startswith("release/") and _FILES_MARKER in (pr.body or ""):
                return pr
    return None


def _release_files_from_pr(pr) -> list[str]:
    body = pr.body or ""
    idx = body.find(_FILES_MARKER)
    if idx == -1:
        return []
    line = body[idx + len(_FILES_MARKER):].strip().splitlines()[0]
    try:
        files = json.loads(line)
        return [f for f in files if isinstance(f, str)]
    except json.JSONDecodeError:
        return []


def _read_raw(gh_repo, path: str, ref: str) -> str | None:
    try:
        return gh_repo.get_contents(path, ref=ref).decoded_content.decode("utf-8")
    except Exception:
        return None


def _workflow_chart_entries(text: str) -> list[dict[str, str]]:
    """Chart name:version pairs from a governed-deploy workflow's
    multi_deployments_json block (line scan — the block is JSON-in-YAML).
    This is the exact deploy set for that environment: prl1_only charts are
    absent from the PRD workflow, df_images from all of them."""
    entries: list[dict[str, str]] = []
    name = None
    for line in (text or "").splitlines():
        s = line.strip().rstrip(",")
        if '"helm_chart_name"' in s and ":" in s:
            name = s.split(":", 1)[1].strip().strip('"')
        elif '"helm_chart_version"' in s and ":" in s and name:
            entries.append({"name": name, "tag": s.split(":", 1)[1].strip().strip('"')})
            name = None
    return entries


class PromoteReleaseInput(BaseModel):
    target: str = Field(..., description="Branch to promote the release file-set to: uat, prd, or prl1.")
    release_branch: str = Field(
        default="",
        description="Release branch (release/<slug>). Empty = the latest release PR's branch.",
    )
    deployment_repo: str = Field(
        default="",
        description="Deployment repo (owner/repo) the release lives in. Empty = the configured default.",
    )


@tool(args_schema=PromoteReleaseInput)
def promote_release(target: str, release_branch: str = "", deployment_repo: str = "") -> str:
    """Promote the current release's FILE-SET to the next environment branch
    (SIT -> UAT -> PRD/PRL1): copies the release's changed files verbatim onto the
    target via a short-lived change branch + PR (auto-merged when allowed)."""
    t = target.strip().lower()
    branch_map = {
        "uat": settings.uat_branch,
        "prd": settings.prd_branch,
        "prod": settings.prd_branch,
        "prl1": settings.prl1_branch,
    }
    if t not in branch_map:
        return json.dumps({"ok": False, "error": f"Unknown target '{target}' (use uat, prd or prl1)."})
    target_branch = branch_map[t]

    try:
        repo_full = str(deployment_repo or "").strip() or active_deploy_repo()
        gh_repo = _get_github_client().get_repo(repo_full)
    except Exception as e:
        return json.dumps({"ok": False, "error": f"GitHub error: {e}"})

    pr = None
    if not release_branch:
        pr = _latest_release_pr(gh_repo)
        if pr is None:
            return json.dumps({"ok": False, "error": "No release PR with a file marker found — create a release first."})
        release_branch = pr.head.ref
        files = _release_files_from_pr(pr)
    else:
        pr = _latest_release_pr(gh_repo)
        files = _release_files_from_pr(pr) if pr and pr.head.ref == release_branch else []
    if not files:
        return json.dumps({"ok": False, "error": f"Could not determine the release file list for {release_branch}."})

    # Copy the file-set verbatim from the release branch onto a change branch of target.
    work = f"change/release/{uuid.uuid4().hex[:8]}"
    try:
        base_ref = gh_repo.get_git_ref(f"heads/{target_branch}")
        gh_repo.create_git_ref(f"refs/heads/{work}", base_ref.object.sha)
        changed = []
        for path in files:
            content = _read_raw(gh_repo, path, release_branch)
            if content is None:
                continue
            current = _read_raw(gh_repo, path, work)
            if current == content:
                continue
            message = f"Promote release file {path} -> {target_branch}"
            try:
                existing = gh_repo.get_contents(path, ref=work)
                gh_repo.update_file(path, message, content, existing.sha, branch=work)
            except Exception:
                gh_repo.create_file(path, message, content, branch=work)
            changed.append(path)
        if not changed:
            try:
                gh_repo.get_git_ref(f"heads/{work}").delete()
            except Exception:
                pass
            return json.dumps({
                "ok": True, "action": "no_change",
                "note": f"{target_branch} already carries the release file-set.",
            })
        release_name = (pr.title if pr else release_branch)
        promo_pr = gh_repo.create_pull(
            title=f"{release_name} (→ {target_branch})",
            body=f"Promotes the release file-set from {release_branch}.",
            head=work, base=target_branch,
        )
        merged, detail = _merge_pr(promo_pr, "squash")
        if merged:
            # BQ capture: the promoted env's governance workflow on the release
            # branch IS that env's exact deploy set — record one 'deployed' event
            # per chart so per-environment state/stats include UAT/PRD/PRL1
            # promotions. Best-effort; never fails the promotion.
            try:
                from . import release_queue as _rq

                key = "prd" if t in ("prd", "prod") else t
                wf_text = _read_raw(
                    gh_repo,
                    f".github/workflows/deploy_with_sdlc_governance_{key}.yaml",
                    release_branch,
                )
                charts = _workflow_chart_entries(wf_text or "")
                if charts:
                    _rq.record_deployment(
                        environment=key,
                        artifacts=charts,
                        deployment_repo=repo_full,
                        pr_number=promo_pr.number,
                        note="release_promoted",
                    )
            except Exception:
                pass
        return json.dumps({
            "ok": True,
            "action": "release_promoted" if merged else "promotion_pending",
            "target": target_branch,
            "files": changed,
            "pr_number": promo_pr.number,
            "pr_url": promo_pr.html_url,
            "note": (
                f"Release file-set promoted to {target_branch} via PR #{promo_pr.number}"
                f" ({'merged' if merged else detail})."
            ),
        }, indent=2)
    except Exception as e:
        return json.dumps({"ok": False, "error": f"Promotion failed: {e}"})
