{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "release-copilot.fullname" . }}
  labels:
    {{- include "release-copilot.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.gateway.port.number }}
        name: {{ .Values.gateway.port.name }}
        protocol: {{ .Values.gateway.port.protocol }}
      hosts:
        {{- toYaml .Values.virtualService.hosts | nindent 8 }}
      {{- with .Values.gateway.tls }}
      tls:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
